export const EXAMPLE_CONST = 'EXAMPLE_CONST'

export const SET_SESSIONS = 'SET_SESSIONS'

export const SELECT_TAG = 'SELECT_TAG'
export const UNSELECT_TAG = 'UNSELECT_TAG'
export const CLEAR_SELECTED_TAGS = 'CLEAR_SELECTED_TAGS'

export const ADD_TO_SCHEDULE = 'ADD_TO_SCHEDULE'
export const REMOVE_FROM_SCHEDULE = 'REMOVE_FROM_SCHEDULE'
export const CLEAR_SCHEDULE = 'CLEAR_SCHEDULE'

export const SET_TAG_ANY_TRUE = 'SET_TAG_ANY_TRUE'
export const SET_TAG_ANY_FALSE = 'SET_TAG_ANY_FALSE'

export const SET_USER = 'SET_USER'
export const SET_ERROR = 'SET_ERROR'
export const SET_LOADING = 'SET_LOADING'
